name = "Pphqhqcobblemon"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3da7972b4d25ac517d2348bf7d0f8067695c49cc993d0c198ed6570d6f6c7ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"
