name = "Pphqhqcobblemon"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0047d54522197ee2c189d83959a15811e040df50d261ebe066b4db4ed876a86b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"
