name = "Pphqhqcobblemon"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca1d043f0f27129b1dbac01a81bd97b01df123736127d867330d10fa83bfb07d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"
