name = "Pphqhqcobblemon"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7109a040ea18aaa700a3a0349ea0a7f7e8e2c1109feee7cee1c168e0585bee2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"
