name = "Pphqhqcobblemon"
version = "1.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6e7c2dd05c09f6b63418ca169f5808a0a37847fc16a3860593ca1bde9d6d725"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.90"
